imports_granularity = "Crate"
reorder_imports =  true

newline_style = "Unix"

chain_width = 80
spaces_around_ranges = false
binop_separator = "Black"
reoder_impl_items = false
match_arm_leading_pipes = "Preserve"
match_arm_blocks = false
match_block_trailing_comma = true
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true

comment_width = 100
wrap_comments = true