[package]
name = "blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version = "1.0",features=["derive"]}
tokio = {version = "1", features=["full"]}
macros = {path = "./macros/"}

sha2 = {version = "0.11.0-rc.1"}
hex = {version = "0.4"}
num = "0.4.3"
expand = "0.3.0"
